name: Bump version and release

on:
  push:
    branches:
      - main

jobs:
  quality:
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: Fetch repo
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'

      - name: Configure poetry
        shell: bash
        run: poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: poetry install

      - name: Linting
        run: poetry run flake8 --exclude .git,__pycache__,build,dist,.venv --per-file-ignores="__init__.py:F401"

      - name: Run unit tests
        run: poetry run pytest

  bump-version:
    runs-on: ubuntu-latest
    needs: quality
    permissions:
      contents: write
    steps:
      - name: Fetch repo
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'

      - name: Configure poetry
        shell: bash
        run: poetry config virtualenvs.in-project true

      - name: Bump version
        run: poetry version patch

      - name: Get new version
        run: echo "current_version=$(grep 'version' pyproject.toml | cut -d ' ' -f3 | tr -d '"')" >> $GITHUB_ENV

      - name: Tag and commit
        run: |
          git config user.name "githubactions"
          git config user.email "githubactions@github.com"
          git tag -a v${{ env.current_version }} -m "v${{ env.current_version }}"
          git add pyproject.toml
          git commit -m "bump version"
          git push --follow-tags origin main
